server {
    listen 80;

    server_name wpset.org;
    server_name www.wpset.org;

    location / {
        return 301 https://wpset.org$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.wpset.org;

    ssl_certificate /etc/letsencrypt/live/wpset.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wpset.org/privkey.pem;

    location / {
        return 301 https://wpset.org$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name wpset.org;

    charset utf-8;
    root /srv/http/wpset.org;

    ssl_certificate /etc/letsencrypt/live/wpset.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wpset.org/privkey.pem;

    location / {
        proxy_pass http://localhost:3004;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    location = /sharing-image/premium/ {
        return 301 https://wpset.org/sharing-image/#premium;
    }

    location = /robots.txt {
        log_not_found off;
        access_log off;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location ~ /\. {
        deny all;
    }
}
